name: Run tests and publish report
on: [workflow_dispatch,push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        python-version: ["3.10"]  
    steps:
      - uses: actions/checkout@v3
      - name: Checkout gh-pages to github runner
        uses: actions/checkout@v2  
        with:
          ref: gh-pages
          path: ./.github/gh-pages
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
      - name: Run tests and generate Allure results  
        run:
          pytest --alluredir=allure-results
        continue-on-error: true
      - name: Make directory history
        run:
          sudo mkdir -p allure-results/history
      - name: Copy history
        run:
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-results

      - name: Publish Allure report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-results
